# Form implementation generated from reading ui file 'avwiki_actor_settings.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AvwikiActorSettings(object):
    def setupUi(self, AvwikiActorSettings):
        AvwikiActorSettings.setObjectName("AvwikiActorSettings")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AvwikiActorSettings.sizePolicy().hasHeightForWidth())
        AvwikiActorSettings.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AvwikiActorSettings)
        self.horizontalLayout.setContentsMargins(24, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_force_avwiki_actor = QtWidgets.QCheckBox(parent=AvwikiActorSettings)
        self.checkBox_force_avwiki_actor.setEnabled(False)
        self.checkBox_force_avwiki_actor.setObjectName("checkBox_force_avwiki_actor")
        self.horizontalLayout.addWidget(self.checkBox_force_avwiki_actor)

        self.retranslateUi(AvwikiActorSettings)
        QtCore.QMetaObject.connectSlotsByName(AvwikiActorSettings)

    def retranslateUi(self, AvwikiActorSettings):
        _translate = QtCore.QCoreApplication.translate
        self.checkBox_force_avwiki_actor.setToolTip(_translate("AvwikiActorSettings", "仅在上级“使用 AV-Wiki 获取演员真实名字”开启时生效。开启后所有作品都会尝试查询 AV-Wiki；查询失败会保留原演员名，但会增加网络请求。"))
        self.checkBox_force_avwiki_actor.setText(_translate("AvwikiActorSettings", "强制使用 AV-Wiki（所有作品）"))
