# Form implementation generated from reading ui file 'D:\AI Agent\MDCx\mdcx\views\log_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogPage(object):
    def setupUi(self, page_log):
        page_log.setObjectName("page_log")
        self.textBrowser_log_main_2 = QtWidgets.QTextBrowser(parent=page_log)
        self.textBrowser_log_main_2.setGeometry(QtCore.QRect(28, 421, 790, 271))
        self.textBrowser_log_main_2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.textBrowser_log_main_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_log_main_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.textBrowser_log_main_2.setReadOnly(True)
        self.textBrowser_log_main_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.textBrowser_log_main_2.setOpenExternalLinks(True)
        self.textBrowser_log_main_2.setOpenLinks(True)
        self.textBrowser_log_main_2.setObjectName("textBrowser_log_main_2")
        self.pushButton_start_cap2 = QtWidgets.QPushButton(parent=page_log)
        self.pushButton_start_cap2.setGeometry(QtCore.QRect(680, 13, 120, 40))
        self.pushButton_start_cap2.setObjectName("pushButton_start_cap2")
        self.textBrowser_log_main = QtWidgets.QTextBrowser(parent=page_log)
        self.textBrowser_log_main.setGeometry(QtCore.QRect(28, 0, 790, 421))
        self.textBrowser_log_main.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.textBrowser_log_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textBrowser_log_main.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_log_main.setMidLineWidth(0)
        self.textBrowser_log_main.setReadOnly(True)
        self.textBrowser_log_main.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.textBrowser_log_main.setOpenExternalLinks(True)
        self.textBrowser_log_main.setOpenLinks(True)
        self.textBrowser_log_main.setObjectName("textBrowser_log_main")
        self.pushButton_show_hide_logs = QtWidgets.QPushButton(parent=page_log)
        self.pushButton_show_hide_logs.setGeometry(QtCore.QRect(0, 650, 40, 40))
        self.pushButton_show_hide_logs.setMouseTracking(True)
        self.pushButton_show_hide_logs.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\AI Agent\\MDCx\\mdcx\\views\\../../MDCx-py-20220407/edit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_show_hide_logs.setIcon(icon)
        self.pushButton_show_hide_logs.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_show_hide_logs.setCheckable(False)
        self.pushButton_show_hide_logs.setAutoDefault(False)
        self.pushButton_show_hide_logs.setDefault(False)
        self.pushButton_show_hide_logs.setObjectName("pushButton_show_hide_logs")
        self.pushButton_view_failed_list = QtWidgets.QPushButton(parent=page_log)
        self.pushButton_view_failed_list.setGeometry(QtCore.QRect(565, 13, 101, 40))
        self.pushButton_view_failed_list.setObjectName("pushButton_view_failed_list")
        self.textBrowser_log_main_3 = QtWidgets.QTextBrowser(parent=page_log)
        self.textBrowser_log_main_3.setEnabled(True)
        self.textBrowser_log_main_3.setGeometry(QtCore.QRect(0, 0, 690, 693))
        self.textBrowser_log_main_3.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.textBrowser_log_main_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_log_main_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.textBrowser_log_main_3.setReadOnly(True)
        self.textBrowser_log_main_3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.textBrowser_log_main_3.setOpenExternalLinks(True)
        self.textBrowser_log_main_3.setOpenLinks(True)
        self.textBrowser_log_main_3.setObjectName("textBrowser_log_main_3")
        self.pushButton_scraper_failed_list = QtWidgets.QPushButton(parent=page_log)
        self.pushButton_scraper_failed_list.setGeometry(QtCore.QRect(20, 13, 531, 40))
        self.pushButton_scraper_failed_list.setObjectName("pushButton_scraper_failed_list")
        self.pushButton_save_failed_list = QtWidgets.QPushButton(parent=page_log)
        self.pushButton_save_failed_list.setGeometry(QtCore.QRect(0, 650, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save_failed_list.setFont(font)
        self.pushButton_save_failed_list.setMouseTracking(True)
        self.pushButton_save_failed_list.setText("")
        self.pushButton_save_failed_list.setIcon(icon)
        self.pushButton_save_failed_list.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_save_failed_list.setCheckable(False)
        self.pushButton_save_failed_list.setAutoDefault(False)
        self.pushButton_save_failed_list.setDefault(False)
        self.pushButton_save_failed_list.setObjectName("pushButton_save_failed_list")
        self.textBrowser_log_main_2.raise_()
        self.textBrowser_log_main.raise_()
        self.pushButton_start_cap2.raise_()
        self.pushButton_show_hide_logs.raise_()
        self.textBrowser_log_main_3.raise_()
        self.pushButton_view_failed_list.raise_()
        self.pushButton_scraper_failed_list.raise_()
        self.pushButton_save_failed_list.raise_()

        self.retranslateUi(page_log)
        QtCore.QMetaObject.connectSlotsByName(page_log)

    def retranslateUi(self, page_log):
        _translate = QtCore.QCoreApplication.translate
        self.textBrowser_log_main_2.setHtml(_translate("LogPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"                <html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"                p, li { white-space: pre-wrap; }\n"
"                </style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span></p></body></html>"))
        self.pushButton_start_cap2.setText(_translate("LogPage", "开始"))
        self.textBrowser_log_main.setHtml(_translate("LogPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"                <html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"                p, li { white-space: pre-wrap; }\n"
"                </style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span></p></body></html>"))
        self.pushButton_view_failed_list.setText(_translate("LogPage", "失败 0"))
        self.textBrowser_log_main_3.setHtml(_translate("LogPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"                <html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"                p, li { white-space: pre-wrap; }\n"
"                </style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span> </p>\n"
"                <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt;\"> </span></p></body></html>"))
        self.pushButton_scraper_failed_list.setText(_translate("LogPage", "当有失败任务时，点击可以一键刮削当前失败列表"))
