# Form implementation generated from reading ui file 'D:\AI Agent\MDCx\mdcx\views\network_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NetworkPage(object):
    def setupUi(self, page_net):
        page_net.setObjectName("page_net")
        self.textBrowser_net_main = QtWidgets.QTextBrowser(parent=page_net)
        self.textBrowser_net_main.setGeometry(QtCore.QRect(30, 0, 790, 682))
        self.textBrowser_net_main.setReadOnly(True)
        self.textBrowser_net_main.setOpenExternalLinks(True)
        self.textBrowser_net_main.setObjectName("textBrowser_net_main")
        self.pushButton_check_net = QtWidgets.QPushButton(parent=page_net)
        self.pushButton_check_net.setGeometry(QtCore.QRect(680, 13, 120, 40))
        self.pushButton_check_net.setObjectName("pushButton_check_net")

        self.retranslateUi(page_net)
        QtCore.QMetaObject.connectSlotsByName(page_net)

    def retranslateUi(self, page_net):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_check_net.setText(_translate("NetworkPage", "开始检测"))
